name: Static Site

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.121.1'

      - name: Build
        run: hugo --minify

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'principal://iam.googleapis.com/projects/712238927167/locations/global/workloadIdentityPools/1660pl'  # 使用你的工作负载身份池ID
          service_account: 'cs1660fl@web1-363623.iam.gserviceaccount.com'

      - id: 'upload-static-files'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: 'public'
          destination: 'cs1660final'
          parent: false
