name: Deploy to GCP Storage

on:
  push:
    branches:
      - main  # This is the branch whose push will trigger the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest  # The type of runner that the job will run on

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # This step checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it

    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2  # This action sets up a Hugo environment for use in actions by downloading a version of Hugo binary and adding to PATH
      with:
        hugo-version: '0.121.1'  # Replace with the version of Hugo you want to use

    - name: Build
      run: hugo --minify  # Runs a set of commands using the runners shell

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1  # This action configures the Google Cloud authentication in a workflow.
      with:
        workload_identity_provider: 'projects/712238927167/locations/global/workloadIdentityPools/1660pl/providers/github-cs1660'  # Replace with your workload identity provider
        service_account: 'cs1660fl@web1-363623.iam.gserviceaccount.com'  # Replace with your service account email

    - name: Upload to Google Cloud Storage
      uses: google-github-actions/upload-cloud-storage@v1  # This action uploads files/folders to a Google Cloud Storage (GCS) bucket.
      with:
        path: public  # The path in your repository to upload from
        destination: gs://cs1660final  # The destination bucket and optional path to upload to
